# This is supposed to be used for deployment on coolify

services:
  # The service that spins up all 3 services at once in one container
  hoppscotch-aio:
    container_name: hoppscotch-aio
    restart: unless-stopped
    build:
      dockerfile: prod.Dockerfile
      context: .
      target: aio
    depends_on:
      hoppscotch-db:
        condition: service_healthy
    # ports:
    #   - "3000:3000"
    #   - "3100:3100"
    #   - "3170:3170"
    #   - "3080:80"

  # The preset DB service, you can delete/comment the below lines if
  # you are using an external postgres instance
  # This will be exposed at port 5432
  hoppscotch-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${HOPPSCOTCH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${HOPPSCOTCH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${HOPPSCOTCH_POSTGRES_DB}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
